feat: do not allow negative timestamps as input
dcaf-labs/pre-authorized-debit pull request #28
Opened 2023-09-09 20:57 UTC by dcaf-mocha

2023-09-09 20:59 UTC, dcaf-mocha commented on programs/pre-authorized-debit-v1/src/errors.rs
> +    InvalidTimestamp, // 6014 or 0x177E
I dont think this will ever get called. Rust will just try and parse the bytes as u64 if a client tries passing a negative value.

2023-09-09 21:47 UTC, dcaf-matcha requested changes
Can you add a test where you send in u64 max and see what happen? I wonder if it'll turn that into a huge negative number coz of 2's complement or just panic

2023-09-10 16:39 UTC, dcaf-matcha requested changes
After thinking through it again, I think we can abandon most of the changes in this PR and just support negative timestamps. There are a few semi-related changes to make also. I'll itemize them along with the main steps here:

1. Revert everything to what it is on main
2. All timestamps on main afaik are already passed in and stored as i64 types which is valid. The only time-based parameter that isn't passed in or stored as i64 is `repeat_frequency_seconds` for a recurring pre-authorization. I think this is okay given that has to be positive always but to avoid weird size issues, we should add a validation in `init_pre_authorization` that checks that this value is < i64::MAX as u64.
3. Even though the actual values, by the time the runtime gets to compute_current_cycle will never satisfy current_timestamp < activation_timestamp due to prior checks, we should still assert this and error out if that is the case to avoid weird bugs that can be introduced in future iterations when the original check is removed. I'd also unit test this logic.
4. Add integration test cases for changes in point 2 above. Maybe also add a test case where you set the timestamps to negative and things still function as expected.

2023-09-10 17:10 UTC, dcaf-mocha commented
Closing in place of https://github.com/dcaf-labs/pre-authorized-debit/pull/31

2023-09-10 17:10 UTC, closed without merging